# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-24.04

name: "2.0.$(Rev:r)"

steps:
  - task: DownloadSecureFile@1
    name: secretsHeader # This name is used to reference the file path later
    displayName: "Download secrets.h"
    inputs:
      secureFile: "secrets.h"
  - task: DownloadSecureFile@1
    name: envFile # Unique ID for this file
    displayName: "Download .env"
    inputs:
      secureFile: ".env"
  - script: |
      mkdir $(Pipeline.Workspace)/build
      cp -r $(Pipeline.Workspace)/s/** $(Pipeline.Workspace)/build
      cp $(secretsHeader.secureFilePath) $(Pipeline.Workspace)/build/src/secrets.h
      cp $(envFile.secureFilePath) $(Pipeline.Workspace)/build/.env
      cd $(Pipeline.Workspace)/build
      curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
      python3 get-platformio.py
      mkdir -p /usr/local/bin
      ln -s ~/.platformio/penv/bin/platformio /usr/local/bin/platformio
      ln -s ~/.platformio/penv/bin/pio /usr/local/bin/pio
      ln -s ~/.platformio/penv/bin/piodebuggdb /usr/local/bin/piodebuggdb
      sed -i -e "s/0\.0\.0/$(Build.BuildNumber)/g" $(Pipeline.Workspace)/build/src/main.cpp
      sed -i -e "s/#define DEBUG 1/#define DEBUG 0/g" $(Pipeline.Workspace)/build/src/main.cpp
      cp $(Pipeline.Workspace)/build/deploy/espfota.json $(Pipeline.Workspace)/build/deploy/espfota_pre.json
      sed -i -e "s/X.X.X/$(Build.BuildNumber)/g" $(Pipeline.Workspace)/build/deploy/espfota.json
      sed -i -e "s/firmware.bin/firmware_epd7.bin/g" $(Pipeline.Workspace)/build/deploy/espfota.json
      sed -i -e "s/X.X.X/$(Build.BuildNumber)/g" $(Pipeline.Workspace)/build/deploy/espfota_pre.json
      sed -i -e "s/firmware.bin/firmware_epd7_pre.bin/g" $(Pipeline.Workspace)/build/deploy/espfota_pre.json
      pio pkg install
      pio run
      if [ ! -f "./.pio/build/ESP32-C6-DevKitM-1/firmware.bin" ]; then
        echo "##[error]Build failed: firmware.bin was not created."
        exit 1
      fi
      mkdir artifact
      cp ./.pio/build/ESP32-C6-DevKitM-1/firmware.bin ./artifact/firmware_epd7.bin
      cp ./deploy/espfota.json ./artifact/espfota_epd7.json
      cp ./.pio/build/ESP32-C6-DevKitM-1/firmware.bin ./artifact/firmware_epd7_pre.bin
      cp ./deploy/espfota_pre.json ./artifact/espfota_epd7_pre.json
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(Pipeline.Workspace)/build/artifact/"
      artifact: "epaper_fw_epd7_$(Build.BuildNumber)"
      publishLocation: "pipeline"
