name: "Dev Build"
run-name: "b3.0.${{ github.run_number }}"

on:
  push:
    branches:
      - paper-l

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Inject secrets.h
        env:
          SECRETS_H: ${{ secrets.SECRETS_H }}
        run: |
          echo "$SECRETS_H" > src/secrets.h

      - name: Inject .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV_FILE" > .env

      - name: Set version and debug flag
        run: |
          newversion="${{ github.run_name }}"
          echo "Version: $newversion"
          
          # Replace version in types.h
          sed -i -e "s/0\.0\.0/$newversion/g" src/types.h
          
          # Replace DEBUG flag in types.h
          sed -i -e "s/#define DEBUG 0/#define DEBUG 1/g" src/types.h
          
          # Replace FOTA JSON content
          sed -i -e "s/X.X.X/$newversion/g" deploy/espfota.json
          sed -i -e "s|http://sample.de/firmware.bin|http://${{ secrets.S3_BUCKET_NAME }}/firmware.bin|g" deploy/espfota.json
          sed -i -e "s/firmware.bin/firmware_epd13_dev.bin/g" deploy/espfota.json

      - name: Install PlatformIO Dependencies
        run: pio pkg install

      - name: Run PlatformIO Build
        run: pio run

      - name: Verify and Prepare Artifacts
        run: |
          if [ ! -f "./.pio/build/ESP32-C6-DevKitM-1/firmware.bin" ]; then
            echo "::error::Build failed: firmware.bin was not created."
            exit 1
          fi
          
          ls -la
          mkdir artifact
          cp ./.pio/build/ESP32-C6-DevKitM-1/firmware.bin ./artifact/firmware_epd13_dev.bin
          cp ./deploy/espfota.json ./artifact/espfota_epd13_dev.json

      - name: Publish Pipeline Artifact
        uses: actions/upload-artifact@v4
        with:
          name: epaper_fw_epd13_dev_${{ github.run_name }}
          path: artifact/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: S3 Upload Firmware and JSON
        run: |
          # Upload files to the root of the bucket with public-read ACL
          aws s3 cp ./artifact/ s3://${{ secrets.S3_BUCKET_NAME }}/ --recursive --exclude "*" --include "firmware_epd13_dev*" --include "espfota_epd13_dev*" --acl public-read

      - name: Create Archive
        run: |
          # Create a ZIP archive of the artifacts
          cd artifact
          zip -r ../epaper_fw_epd13_dev_${{ github.run_name }}.zip ./*
          cd ..

      - name: S3 Upload Archive
        run: |
          # Upload the ZIP archive to the root of the bucket
          aws s3 cp epaper_fw_epd13_dev_${{ github.run_name }}.zip s3://${{ secrets.S3_BUCKET_NAME }}/ --acl public-read

